export const GET_USER = "GET_USER";
export const LOG_OUT = "LOG_OUT";

export const GET_DAILY_NEW_USERS_WITH_DATE = "GET_DAILY_NEW_USERS_WITH_DATE";
export const GET_CUMULATIVE_USERS_WITH_DATE = "GET_CUMULATIVE_USERS_WITH_DATE";

export const GET_FILE_TO_DOWNLOAD = "GET_FILE_TO_DOWNLOAD";

export const SET_CHANGE_STREAM_SOCKET = "SET_CHANGE_STREAM_SOCKET";
export const CHANGE_NEW_DATA = "CHANGE_NEW_DATA";
export const GET_NEW_DATA = "GET_NEW_DATA";
export const RESET_NEW_DATA = "RESET_NEW_DATA";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const ADD_POST = "ADD_POST";
export const END_ADD_POST_STATUS = "END_ADD_POST_STATUS";
export const GET_POSTS = "GET_POSTS";
export const GET_MAIN_TOP_SLIDE_POSTS = "GET_MAIN_TOP_SLIDE_POSTS";
export const GET_LATEST_POSTS = "GET_LATEST_POSTS";
export const GET_POST = "GET_POST";
export const ADD_POST_COMMENT = "ADD_POST_COMMENT";
export const END_ADD_POST_COMMENT_STATUS = "END_ADD_POST_COMMENT_STATUS";
export const DELETE_POST_COMMENT = "DELETE_POST_COMMENT";
export const END_DELETE_POST_COMMENT_STATUS = "END_DELETE_POST_COMMENT_STATUS";
export const EDIT_POST_COMMENT = "EDIT_POST_COMMENT";
export const END_EDIT_POST_COMMENT_STATUS = "END_EDIT_POST_COMMENT_STATUS";
